### ISSUE TITLE
Needed libraries not found from OSX binary

### ISSUE THREAD

**Issue by hickst** [technomancy/grenchman#21]
Download and run of OSX binary on 10.8.5 produces dynamic link error:

> grench
dyld: Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /usr/local/bin/grench
  Reason: image not found
Trace/BPT trap

Note there is no /usr/local/opt directory on my system (default installation)

> uname -a
Darwin twelf 12.5.0 Darwin Kernel Version 12.5.0: Mon Jul 29 16:33:49 PDT 2013; root:xnu-2050.48.11~1/RELEASE_X86_64 x86_64

> otool -L grench
grench:
    /usr/local/opt/libffi/lib/libffi.6.dylib (compatibility version 7.0.0, current version 7.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
    /usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)

> mdfind -name libffi
/System/Library/Tcl/8.5/Ffidl0.6.1/libFfidl0.6.1.dylib
/System/Library/Tcl/8.4/Ffidl0.6.1/libFfidl0.6.1.dylib
/usr/lib/libffi.dylib         # appears to be version 1.0.0

**Comment by suculent** [comment]
I'm aware of total mess inside my computer, that caused this... using homebrew and macports together, I've caused this situation by uninstalling macports (I thought I won't need it anymore).

Fixed using macports:
    
    $ sudo port install libffi

**Comment by ypapax** [comment]
`brew reinstall libffi` helped me
