### ISSUE TITLE
Running leiningen tasks doesn't work in a project-local REPL

### ISSUE THREAD

**Issue by benwbooth** [technomancy/grenchman#26]
This is what I tried:

```
$ lein new app hello
$ cd hello
$ lein run
Hello, World!
$ lein repl :headless
$ LEIN_REPL_PORT=`cat .nrepl-port` grench lein run # in another terminal session
  Unknown status: 19:namespace-not-found
  Unknown status: 5:error
```

It seems like setting the ns to leiningen.core.main is giving a namespace-not-found error, but I have no idea why.

**Comment by sullerandras** [comment]
@technomancy Is there any way to run lein tasks with grench? How can we start that "nREPL session on Leiningen"? 

`grench lein run` says we need to start `lein repl :headless` outside the project directory, but it does not work, it says `Unknown status: 19:namespace-not-found`.

**Comment by technomancy** [comment]
You are correct about how it's supposed to work, but the problem you're
describing is different from the one discussed in this issue; it is
being tracked in #34.
