### ISSUE TITLE
Debian Jessie now uses libffi6 instead of 5

### ISSUE THREAD

**Issue by Alloyed** [technomancy/grenchman#27]
The upshot of which is that the Wheezy binary now links to a nonexistent libffi, but the Ubuntu binary runs just fine.
the version in Jessie/Sid is 3.1-2:
https://packages.debian.org/jessie/libffi6
And the version the ubuntu package was last tested against apparently was 3.0.13
http://packages.ubuntu.com/raring/libffi6
which has been bumped up to 3.1-ish? which is close enough I'd think to say it works there too:
http://packages.ubuntu.com/trusty/libffi6

**Comment by technomancy** [comment]
Thanks; I've updated the web site so it lists Jessie under the second binary instead of the first.

If anyone knows additional Ubuntu versions it works with, I can add them to the list.
