### ISSUE TITLE
Precompiled binaries cannot be downloaded from S3

### ISSUE THREAD

**Issue by gws** [technomancy/grenchman#30]
At the time of this writing all of the download links on http://leiningen.org/grench.html are unavailable.

Fetching https://grenchman.s3.amazonaws.com/downloads/grench-0.2.0-debian-7:

```xml
<Error>
  <Code>AllAccessDisabled</Code>
  <Message>All access to this object has been disabled</Message>
  <RequestId>66A583042E4636FA</RequestId>
  <HostId>lztFuukq6sLsdTuGGIXW7MmCxfjAoC27qbaw1n+yDy/6z9LdUAlWIBIfdnHlFtqkCuqAPpj9qG0=</HostId>
</Error>
```

**Comment by hyPiRion** [comment]
This is probably related to <http://librelist.com/browser//leiningen/2015/1/3/downloads-bucket/>.

**Comment by gws** [comment]
That makes sense, thanks.

GitHub can host build artifacts alongside releases, would that be a viable option?

**Comment by mshenfield** [comment]
:+1:

**Comment by danielcompton** [comment]
Is it possible to get a copy of the binaries and attach them to https://github.com/technomancy/grenchman/releases/tag/0.2.0?

**Comment by technomancy** [comment]
I have tried attaching them to this release; unfortunately it seems there is a bug in the GitHub upload functionality that prevents them from appearing. It just says "Delete and try uploading this file again."

**Comment by ddossot** [comment]
Did you look at https://packagecloud.io/ ? They have a free tier for public repos.

**Comment by technomancy** [comment]
It looks like packagecloud is about storing OS-level packages. The files I have are statically-linked binaries, not .debs or .rpms.

**Comment by ddossot** [comment]
Sorry about that :doh:

What about uploading the file as part of a GitHub site? Too cumbersome?

**Comment by technomancy** [comment]
> What about uploading the file as part of a GitHub site? Too cumbersome?

I haven't used GitHub sites before. If it's something we get free SSL for that could be added with a pull request I'd be all for it.

The files and their signatures are here: http://leiningen.org/grench/grench.tar.gz

**Comment by ddossot** [comment]
I've built a download site prototype in my fork and published it here: https://unbounce.github.io/grenchman/

If you like it, I'll send a pull request over.

**Comment by technomancy** [comment]
> If you like it, I'll send a pull request over.

That looks great; thanks.

If you could include a tl;dr in the PR if it's only a couple of steps
to publish it out that would be great; if it's more involved maybe a
link to the relevant docs would allow this happen more smoothly.

Thanks.

**Comment by ddossot** [comment]
Mmmh I can't send a PR because there's no `gh-pages` in `technomancy/grenchman`. Could you create this branch?

After pulling PR in, I believe the site should become live immediately.

**Comment by technomancy** [comment]
> Mmmh I can't send a PR because there's no `gh-pages` in `technomancy/grenchman`. Could you create this branch?

Sure thing; just created.

**Comment by ddossot** [comment]
PR is ready: https://github.com/technomancy/grenchman/pull/32

Let's hope it works :smile:

**Comment by technomancy** [comment]
Thanks! I went ahead and left the "downloads" section in the original grench.html and updated the links therein, but if anyone hits https://technomancy.github.io/grenchman they'll see your nice downloads page too.

**Comment by ddossot** [comment]
Great! So glad it worked :dancers:

**Comment by ddossot** [comment]
@technomancy Unfortunately, the links for all downloads except debian are broken here: http://leiningen.org/grench.html#download

The broken links contain path with `/downloads/downloads/` instead of just `/downloads/`

**Comment by technomancy** [comment]
Thanks for the heads-up; fixed.
