### ISSUE TITLE
Port repl to lambda-term

### ISSUE THREAD

**Issue by martindemello** [technomancy/grenchman#35]
https://github.com/diml/lambda-term

Pros:
* More advanced repl features
* The other repl enhancement requests could either be done more easily with existing lambda-term features, or contributed to lambda-term for the good of all of us

Cons:
* Adds a bunch of dependencies (though it removes the dependency on libreadline)

**Comment by technomancy** [comment]
Hi; unfortunately this project is basically abandonware. If you are interested in pursuing further development on it, I can point to your fork in the readme, but I am no longer maintaining it.

**Comment by martindemello** [comment]
ah, okay - no worries. i saw it linked from the nrepl repo [https://github.com/clojure/tools.nrepl/wiki/Extensions], so i figured it was extant.

**Comment by technomancy** [comment]
Yeah, it is currently functional as far as I know; just not undergoing any further development.
